apiVersion: template.openshift.io/v1
kind: Template
labels:
  template: nginx-tempplate
metadata:
  annotations:
    description: Creates the ImageStream for nginx
    iconClass: icon-nginx
    openshift.io/display-name: Nginx HTTP server image stream
    openshift.io/long-description: 
  labels:
  name: ${APP_NAME}
objects:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    name: ${APP_NAME}
    namespace: ${NAMESPACE} 
    selfLink: >-
      /apis/image.openshift.io/v1/namespaces/${NAMESPACE}/imagestreams/${APP_NAME}
    generation: 1
    labels:
      app: ${APP_NAME}
  spec:
    lookupPolicy:
      local: false
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    generation: 2
    labels:
      app: ${APP_NAME}
    name: nginx-112-rhel7
    namespace: ${NAMESPACE}
  spec:
    lookupPolicy:
      local: false
    tags:
    - annotations:
        openshift.io/imported-from: registry.access.redhat.com/rhscl/${NGINX_VERSION}-rhel7
      from:
        kind: DockerImage
        name: registry.access.redhat.com/rhscl/${NGINX_VERSION}-rhel7
      generation: 2
      importPolicy: {}
      name: latest
      referencePolicy:
        type: Source
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    name: ${APP_NAME}
    namespace: ${NAMESPACE}
    labels:
      app: ${APP_NAME}
  spec:
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: '${APP_NAME}:latest'
    resources: {}
    successfulBuildsHistoryLimit: 5
    failedBuildsHistoryLimit: 5
    source:
      git:
        ref: master
        uri: 'https://github.com/randalizer/httpd-nginx'
      type: Git
    strategy:
      type: Source
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: '${NGINX_VERSION}-rhel7:latest'
        env: []
    triggers:
      - type: ImageChange
        imageChange: {}
      - type: ConfigChange
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: ${APP_NAME}-pvc  
  spec:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 5Gi
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    name: ${APP_NAME}
    namespace: ${NAMESPACE}
    labels:
      app: ${APP_NAME}
  spec:
    strategy:
      type: Rolling
      rollingParams:
        updatePeriodSeconds: 1
        intervalSeconds: 1
        timeoutSeconds: 600
        maxUnavailable: 25%
        maxSurge: 25%
      resources: {}
      activeDeadlineSeconds: 21600
    triggers:
      - type: ConfigChange
      - type: ImageChange
        imageChangeParams:
          automatic: true
          containerNames:
            - ${APP_NAME}
          from:
            kind: ImageStreamTag
            namespace: ${NAMESPACE}
            name: '${APP_NAME}:latest'
    replicas: 2
    revisionHistoryLimit: 10
    test: false
    selector:
      app: ${APP_NAME}
      deploymentconfig: ${APP_NAME}
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: ${APP_NAME}
          deploymentconfig: ${APP_NAME}
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
      spec:
        volumes: 
          - name: ${APP_NAME}-static-content
            persistentVolumeClaim:
              claimName: ${APP_NAME}-pvc
        containers:
          - name: ${APP_NAME}
            image: >-
              image-registry.openshift-image-registry.svc:5000/${NAMESPACE}/${APP_NAME}
            ports:
              - containerPort: 8080
                protocol: TCP
            resources: {}
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
            imagePullPolicy: Always
            volumeMounts:
              - name: ${APP_NAME}-static-content
                mountPath: /var/www/content
        restartPolicy: Always
        terminationGracePeriodSeconds: 30
        dnsPolicy: ClusterFirst
        securityContext: {}
        schedulerName: default-scheduler
  status:
    observedGeneration: 2
    details:
      message: config change
      causes:
        - type: ConfigChange
    availableReplicas: 2
    unavailableReplicas: 0
    latestVersion: 2
    updatedReplicas: 2
    replicas: 2
    readyReplicas: 2
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: ${APP_NAME}
    name: ${APP_NAME}
    namespace: ${NAMESPACE}
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
    - name: 8443-tcp
      port: 8443
      protocol: TCP
      targetPort: 8443
    selector:
      app: ${APP_NAME}
      deploymentconfig: ${APP_NAME}
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    labels:
      app: ${APP_NAME} 
    name: ${APP_NAME}-defaut-route
    namespace: ${NAMESPACE}
  spec:
    host: wwwdev.randalize.com
    port:
      targetPort: 8080-tcp
    to:
      kind: Service
      name: ${APP_NAME}
parameters:
- description: The name assigned to all of the frontend objects defined in this template.
  displayName: App_Name
  name: APP_NAME
  required: true
- description: The namespace assigned to this template.
  displayName: NameSpace
  name: NAMESPACE
  required: true
- description: Nginx Version
  displayName: Nginx Version
  name: NGINX_VERSION
  required: true
  value: nginx-112


